guest_list = ['DJ Khaled', 'Dagem']
print('Yo ' + guest_list[0] + ", I'm having a Superbowl watch party at the crib. Come thru!")
print('Yo ' + guest_list[1] + ", I'm having a Superbowl watch party at the crib. Come thru!")
print('\nWell it looks like ' + guest_list[0] + " can't make it.")
guest_list[0] = 'Kai' 
print('Yo ' + guest_list[0] + ", I'm having a Superbowl watch party at the crib. Come thru!")
print('\nIt looks like we got a bigger table so now the rest of the gang can slide too.')
guest_list.insert(0, 'Nati')
guest_list.insert(1, 'Kiduse')
guest_list.insert(3, 'Middy')
guest_list.insert(4, 'Matt')
print('Ayo ' + guest_list[0] + ', ' + guest_list[1] + ', ' + guest_list[3] + ', and ' + guest_list[4] + ". I'm having a Superbowl watch party at the crib. Come thru!")
print("\nBoy ain't no way, the new couch I ordered won't get here in time for the big game so it's looking like I can only have 2 people over.")
guest_list.pop(0)
guest_list.pop(0)
guest_list.pop(1)
guest_list.pop(1)
print('\nYo ' + guest_list[0] + ", just letting you know you're still invited so come thru!")
print('\nYo ' + guest_list[1] + ", just letting you know you're still invited so come thru!")